Remove UpdateStatus command, in place of explicit commands.
improving-app/riddl pull request #42
Opened 2023-03-07 00:31 UTC by miguelTaningcoYoppworks

### Issue:

- Currently in the Tenant entity, there is an UpdateStatus command. We want to remove this and in its place have commands that explicitly change the state of the entity.

### Changes:

- Remove UpdateStatus
- Add ActivateTenant
- Add SuspendTenant
- Add TenantActivated
- Add TenantSuspended

### Testing:

- validated riddl

2023-03-20 15:07 UTC, reid-spencer requested changes
Just a few minor adjustments needed.

2023-03-20 15:07 UTC, reid-spencer commented on src/main/riddl/Tenant/tenantMessages.riddl
>  	updatingUser: String
updatingUser should be of type Id(Member) and be named activatingMember

2023-03-20 15:07 UTC, reid-spencer commented on src/main/riddl/Tenant/tenantMessages.riddl
> +	updatingUser: String
updatingUser → suspendingMember
String → Id(Member)

2023-03-20 15:07 UTC, reid-spencer commented on src/main/riddl/Tenant/tenantTypeDefinitions.riddl
> -  Suspended briefly "Tenant is created but administratively suspended"
I think you still need this and its usage on line 21-24 above.  Think of having a query named "GetState" or "GetStatus" ?  The commands to separate the state changes have been added but someone might still need to know what that state is, after it has changed.

2023-03-22 14:42 UTC, miguelTaningcoYoppworks commented
Treating this branch as now unnecessary because of IA-128 which completely changes and overwrites this. Will close this branch and PR.

2023-03-22 14:42 UTC, closed without merging