IA 148 Gateway For Member
improving-app/riddl pull request #51
Opened 2023-03-28 18:46 UTC by AlexWeinstein92

2023-04-11 14:45 UTC, reid-spencer requested changes
I've left some questions on various constructs for you to consider.

2023-04-11 14:45 UTC, reid-spencer commented on src/main/riddl/Gateway/MemberGateway/memberStories.riddl
>      }
Wouldn't it be better also to uncomment these so riddlc can validate the pathIds and the documentation can represent the relationships they imply?

2023-04-11 14:45 UTC, reid-spencer commented on src/main/riddl/Gateway/actorDefinitions.riddl
>  actor App is "The applicaiton the user is using to perform this action"
I would prefer this was specified as an Application definition. I think this was written before the Application/Epic/Actor triangle was established.

2023-04-11 14:45 UTC, reid-spencer commented on src/main/riddl/Gateway/actorDefinitions.riddl
> +actor GatewayAction is "The interface that accepts the request for processing by the backend"
Similar this needs to be written as a Gateway Context

2023-04-11 14:45 UTC, reid-spencer commented on src/main/riddl/Gateway/gateway.riddl
> +    //include "actorDefinitions"
Why comment this out?

2023-04-11 14:45 UTC, reid-spencer commented on src/main/riddl/Gateway/gatewayStories.riddl
> +    //   step from pipe ImprovingApp.MembersContext.MemberEvents "MemberEnrolled" to actor App
Can we uncomment those and get the compiler and hugo documentation to see them?

2023-06-28 18:03 UTC, reid-spencer approved these changes, later dismissed
LGTM

2023-07-04 16:06 UTC, JamesYopp approved these changes
Looks good

2023-07-04 17:12 UTC, merged